name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: primary
    steps:
      - uses: actions/checkout@v2
      - name: Set compatibility date
        run: echo "COMPATIBILITY_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Deploy to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: npx wrangler deploy --compatibility-date ${{ env.COMPATIBILITY_DATE }}
